default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: localhost
  user: postgres
  password: postgres

development:
  <<: *default
  database: tccapi_development

production:
  <<: *default
  database: tccapi_production
  user: postgres
  password: <%= ENV['TCCAPI_DATABASE_PASSWORD'] %>
